# 生產環境
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
services:
  backend:
    build:
      context: ${BACKEND_PATH}
    image: myapp-backend
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ${FRONTEND_PATH}
    image: myapp-frontend
    environment:
      NODE_ENV: production
