# 生產環境 - standalone（docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d）
services:
  backend:
    build:
      additional_contexts:
        src: ${BACKEND_PATH}
    environment:
      NODE_ENV: production

  frontend:
    build:
      additional_contexts:
        src: ${FRONTEND_PATH}
    environment:
      NODE_ENV: production
